# Generated by Django 6.0.3 on 2026-03-07 09:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('date', models.DateField()),
                ('time', models.TimeField()),
                ('location', models.CharField(max_length=255)),
                ('images', models.ImageField(blank=True, null=True, upload_to='event_images/')),
                ('date_added', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
