# Generated by Django 6.0.3 on 2026-03-06 10:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ProfilingInformations',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=50)),
                ('middle_name', models.CharField(max_length=50)),
                ('last_name', models.CharField(max_length=50)),
                ('age', models.IntegerField(blank=True, default=0, null=True)),
                ('birthdate', models.DateField(blank=True, null=True)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('contact_number', models.CharField(max_length=20)),
                ('sex', models.CharField(blank=True, choices=[('male', 'Male'), ('female', 'Female')])),
                ('civil_status', models.CharField(blank=True, choices=[('single', 'Single'), ('married', 'Married'), ('widowed', 'Widowed'), ('divorced', 'Divorced'), ('separated', 'Separated'), ('annulled', 'Annulled'), ('unknown', 'Unknown'), ('live_in', 'Live-in')], max_length=50, null=True)),
                ('educational_background', models.CharField(blank=True, choices=[('elementary_level', 'Elementary Level'), ('elementary_graduate', 'Elementary Graduate'), ('highschool_level', 'High School Level'), ('highschool_graduate', 'High School Graduate'), ('vocational_graduate', 'Vocational Graduate'), ('college_level', 'College Level'), ('college_graduate', 'College Graduate'), ('master_level', 'Master Level'), ('doctorate_level', 'Doctorate Level'), ('doctorate_graduate', 'Doctorate Graduate')], null=True)),
                ('date_added', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='KKAddress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('region', models.CharField(max_length=255)),
                ('province', models.CharField(max_length=255)),
                ('municipality_or_city', models.CharField(max_length=255)),
                ('barangay', models.CharField(max_length=255)),
                ('date_added', models.DateTimeField(auto_now_add=True)),
                ('kk_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='kkprofiles.profilinginformations')),
            ],
        ),
        migrations.CreateModel(
            name='YouthStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('youth_classification', models.CharField(blank=True, choices=[('in_school_youth', 'In-School Youth'), ('out_of_school_youth', 'Out-of-School Youth'), ('working_youth', 'Working Youth')], max_length=50, null=True)),
                ('youth_age_group', models.CharField(blank=True, choices=[('child_youth', 'Child Youth'), ('core_youth', 'Core Youth'), ('young_adult', 'Young Adult')], max_length=50, null=True)),
                ('youth_with_specific_needs', models.CharField(blank=True, choices=[('person_with_disability', 'Person with Disability'), ('children_in_conflict_with_law', 'Children in Conflict with Law'), ('indigenous_people', 'Indigenous People')], max_length=50)),
                ('working_status', models.CharField(blank=True, choices=[('employed', 'Employed'), ('unemployed', 'Unemployed'), ('self_employed', 'Self-Employed'), ('looking_for_job', 'Currently Looking for a Job'), ('not_looking_for_job', 'Not Interested in Looking for a Job')], max_length=50, null=True)),
                ('is_sk_voter', models.BooleanField(blank=True, default=True, null=True)),
                ('is_regular_voter', models.BooleanField(blank=True, default=False, null=True)),
                ('attended_kk_aasembly', models.BooleanField(blank=True, default=True, null=True)),
                ('times_attended', models.IntegerField(default=0)),
                ('did_not_attended_kk_assembly', models.TextField(blank=True)),
                ('date_added', models.DateTimeField(auto_now_add=True)),
                ('kk_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='kkprofiles.profilinginformations')),
            ],
        ),
    ]
