# Generated by Django 6.0.3 on 2026-03-07 07:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kkprofiles', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='kkaddress',
            name='kk_name',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='address', to='kkprofiles.profilinginformations'),
        ),
        migrations.AlterField(
            model_name='youthstatus',
            name='kk_name',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='youth_status', to='kkprofiles.profilinginformations'),
        ),
    ]
